// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/amrohan/expenso-go/ent/predicate"
	"github.com/amrohan/expenso-go/ent/transaction"
)

// TransactionUpdate is the builder for updating Transaction entities.
type TransactionUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionMutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (tu *TransactionUpdate) Where(ps ...predicate.Transaction) *TransactionUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetTitle sets the "title" field.
func (tu *TransactionUpdate) SetTitle(s string) *TransactionUpdate {
	tu.mutation.SetTitle(s)
	return tu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableTitle(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetTitle(*s)
	}
	return tu
}

// SetAmount sets the "amount" field.
func (tu *TransactionUpdate) SetAmount(f float64) *TransactionUpdate {
	tu.mutation.ResetAmount()
	tu.mutation.SetAmount(f)
	return tu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableAmount(f *float64) *TransactionUpdate {
	if f != nil {
		tu.SetAmount(*f)
	}
	return tu
}

// AddAmount adds f to the "amount" field.
func (tu *TransactionUpdate) AddAmount(f float64) *TransactionUpdate {
	tu.mutation.AddAmount(f)
	return tu
}

// SetDescription sets the "description" field.
func (tu *TransactionUpdate) SetDescription(s string) *TransactionUpdate {
	tu.mutation.SetDescription(s)
	return tu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableDescription(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetDescription(*s)
	}
	return tu
}

// ClearDescription clears the value of the "description" field.
func (tu *TransactionUpdate) ClearDescription() *TransactionUpdate {
	tu.mutation.ClearDescription()
	return tu
}

// SetDate sets the "date" field.
func (tu *TransactionUpdate) SetDate(t time.Time) *TransactionUpdate {
	tu.mutation.SetDate(t)
	return tu
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableDate(t *time.Time) *TransactionUpdate {
	if t != nil {
		tu.SetDate(*t)
	}
	return tu
}

// SetCategoryId sets the "categoryId" field.
func (tu *TransactionUpdate) SetCategoryId(i int) *TransactionUpdate {
	tu.mutation.ResetCategoryId()
	tu.mutation.SetCategoryId(i)
	return tu
}

// SetNillableCategoryId sets the "categoryId" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableCategoryId(i *int) *TransactionUpdate {
	if i != nil {
		tu.SetCategoryId(*i)
	}
	return tu
}

// AddCategoryId adds i to the "categoryId" field.
func (tu *TransactionUpdate) AddCategoryId(i int) *TransactionUpdate {
	tu.mutation.AddCategoryId(i)
	return tu
}

// SetAccountId sets the "accountId" field.
func (tu *TransactionUpdate) SetAccountId(i int) *TransactionUpdate {
	tu.mutation.ResetAccountId()
	tu.mutation.SetAccountId(i)
	return tu
}

// SetNillableAccountId sets the "accountId" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableAccountId(i *int) *TransactionUpdate {
	if i != nil {
		tu.SetAccountId(*i)
	}
	return tu
}

// AddAccountId adds i to the "accountId" field.
func (tu *TransactionUpdate) AddAccountId(i int) *TransactionUpdate {
	tu.mutation.AddAccountId(i)
	return tu
}

// SetUserId sets the "userId" field.
func (tu *TransactionUpdate) SetUserId(s string) *TransactionUpdate {
	tu.mutation.SetUserId(s)
	return tu
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableUserId(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetUserId(*s)
	}
	return tu
}

// SetType sets the "type" field.
func (tu *TransactionUpdate) SetType(s string) *TransactionUpdate {
	tu.mutation.SetType(s)
	return tu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableType(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetType(*s)
	}
	return tu
}

// SetStatus sets the "status" field.
func (tu *TransactionUpdate) SetStatus(s string) *TransactionUpdate {
	tu.mutation.SetStatus(s)
	return tu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableStatus(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetStatus(*s)
	}
	return tu
}

// ClearStatus clears the value of the "status" field.
func (tu *TransactionUpdate) ClearStatus() *TransactionUpdate {
	tu.mutation.ClearStatus()
	return tu
}

// SetCurrency sets the "currency" field.
func (tu *TransactionUpdate) SetCurrency(s string) *TransactionUpdate {
	tu.mutation.SetCurrency(s)
	return tu
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (tu *TransactionUpdate) SetNillableCurrency(s *string) *TransactionUpdate {
	if s != nil {
		tu.SetCurrency(*s)
	}
	return tu
}

// ClearCurrency clears the value of the "currency" field.
func (tu *TransactionUpdate) ClearCurrency() *TransactionUpdate {
	tu.mutation.ClearCurrency()
	return tu
}

// Mutation returns the TransactionMutation object of the builder.
func (tu *TransactionUpdate) Mutation() *TransactionMutation {
	return tu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TransactionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TransactionUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TransactionUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TransactionUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tu *TransactionUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Title(); ok {
		_spec.SetField(transaction.FieldTitle, field.TypeString, value)
	}
	if value, ok := tu.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tu.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
	}
	if tu.mutation.DescriptionCleared() {
		_spec.ClearField(transaction.FieldDescription, field.TypeString)
	}
	if value, ok := tu.mutation.Date(); ok {
		_spec.SetField(transaction.FieldDate, field.TypeTime, value)
	}
	if value, ok := tu.mutation.CategoryId(); ok {
		_spec.SetField(transaction.FieldCategoryId, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedCategoryId(); ok {
		_spec.AddField(transaction.FieldCategoryId, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AccountId(); ok {
		_spec.SetField(transaction.FieldAccountId, field.TypeInt, value)
	}
	if value, ok := tu.mutation.AddedAccountId(); ok {
		_spec.AddField(transaction.FieldAccountId, field.TypeInt, value)
	}
	if value, ok := tu.mutation.UserId(); ok {
		_spec.SetField(transaction.FieldUserId, field.TypeString, value)
	}
	if value, ok := tu.mutation.GetType(); ok {
		_spec.SetField(transaction.FieldType, field.TypeString, value)
	}
	if value, ok := tu.mutation.Status(); ok {
		_spec.SetField(transaction.FieldStatus, field.TypeString, value)
	}
	if tu.mutation.StatusCleared() {
		_spec.ClearField(transaction.FieldStatus, field.TypeString)
	}
	if value, ok := tu.mutation.Currency(); ok {
		_spec.SetField(transaction.FieldCurrency, field.TypeString, value)
	}
	if tu.mutation.CurrencyCleared() {
		_spec.ClearField(transaction.FieldCurrency, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TransactionUpdateOne is the builder for updating a single Transaction entity.
type TransactionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionMutation
}

// SetTitle sets the "title" field.
func (tuo *TransactionUpdateOne) SetTitle(s string) *TransactionUpdateOne {
	tuo.mutation.SetTitle(s)
	return tuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableTitle(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetTitle(*s)
	}
	return tuo
}

// SetAmount sets the "amount" field.
func (tuo *TransactionUpdateOne) SetAmount(f float64) *TransactionUpdateOne {
	tuo.mutation.ResetAmount()
	tuo.mutation.SetAmount(f)
	return tuo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableAmount(f *float64) *TransactionUpdateOne {
	if f != nil {
		tuo.SetAmount(*f)
	}
	return tuo
}

// AddAmount adds f to the "amount" field.
func (tuo *TransactionUpdateOne) AddAmount(f float64) *TransactionUpdateOne {
	tuo.mutation.AddAmount(f)
	return tuo
}

// SetDescription sets the "description" field.
func (tuo *TransactionUpdateOne) SetDescription(s string) *TransactionUpdateOne {
	tuo.mutation.SetDescription(s)
	return tuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableDescription(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetDescription(*s)
	}
	return tuo
}

// ClearDescription clears the value of the "description" field.
func (tuo *TransactionUpdateOne) ClearDescription() *TransactionUpdateOne {
	tuo.mutation.ClearDescription()
	return tuo
}

// SetDate sets the "date" field.
func (tuo *TransactionUpdateOne) SetDate(t time.Time) *TransactionUpdateOne {
	tuo.mutation.SetDate(t)
	return tuo
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableDate(t *time.Time) *TransactionUpdateOne {
	if t != nil {
		tuo.SetDate(*t)
	}
	return tuo
}

// SetCategoryId sets the "categoryId" field.
func (tuo *TransactionUpdateOne) SetCategoryId(i int) *TransactionUpdateOne {
	tuo.mutation.ResetCategoryId()
	tuo.mutation.SetCategoryId(i)
	return tuo
}

// SetNillableCategoryId sets the "categoryId" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableCategoryId(i *int) *TransactionUpdateOne {
	if i != nil {
		tuo.SetCategoryId(*i)
	}
	return tuo
}

// AddCategoryId adds i to the "categoryId" field.
func (tuo *TransactionUpdateOne) AddCategoryId(i int) *TransactionUpdateOne {
	tuo.mutation.AddCategoryId(i)
	return tuo
}

// SetAccountId sets the "accountId" field.
func (tuo *TransactionUpdateOne) SetAccountId(i int) *TransactionUpdateOne {
	tuo.mutation.ResetAccountId()
	tuo.mutation.SetAccountId(i)
	return tuo
}

// SetNillableAccountId sets the "accountId" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableAccountId(i *int) *TransactionUpdateOne {
	if i != nil {
		tuo.SetAccountId(*i)
	}
	return tuo
}

// AddAccountId adds i to the "accountId" field.
func (tuo *TransactionUpdateOne) AddAccountId(i int) *TransactionUpdateOne {
	tuo.mutation.AddAccountId(i)
	return tuo
}

// SetUserId sets the "userId" field.
func (tuo *TransactionUpdateOne) SetUserId(s string) *TransactionUpdateOne {
	tuo.mutation.SetUserId(s)
	return tuo
}

// SetNillableUserId sets the "userId" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableUserId(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetUserId(*s)
	}
	return tuo
}

// SetType sets the "type" field.
func (tuo *TransactionUpdateOne) SetType(s string) *TransactionUpdateOne {
	tuo.mutation.SetType(s)
	return tuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableType(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetType(*s)
	}
	return tuo
}

// SetStatus sets the "status" field.
func (tuo *TransactionUpdateOne) SetStatus(s string) *TransactionUpdateOne {
	tuo.mutation.SetStatus(s)
	return tuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableStatus(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetStatus(*s)
	}
	return tuo
}

// ClearStatus clears the value of the "status" field.
func (tuo *TransactionUpdateOne) ClearStatus() *TransactionUpdateOne {
	tuo.mutation.ClearStatus()
	return tuo
}

// SetCurrency sets the "currency" field.
func (tuo *TransactionUpdateOne) SetCurrency(s string) *TransactionUpdateOne {
	tuo.mutation.SetCurrency(s)
	return tuo
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (tuo *TransactionUpdateOne) SetNillableCurrency(s *string) *TransactionUpdateOne {
	if s != nil {
		tuo.SetCurrency(*s)
	}
	return tuo
}

// ClearCurrency clears the value of the "currency" field.
func (tuo *TransactionUpdateOne) ClearCurrency() *TransactionUpdateOne {
	tuo.mutation.ClearCurrency()
	return tuo
}

// Mutation returns the TransactionMutation object of the builder.
func (tuo *TransactionUpdateOne) Mutation() *TransactionMutation {
	return tuo.mutation
}

// Where appends a list predicates to the TransactionUpdate builder.
func (tuo *TransactionUpdateOne) Where(ps ...predicate.Transaction) *TransactionUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TransactionUpdateOne) Select(field string, fields ...string) *TransactionUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Transaction entity.
func (tuo *TransactionUpdateOne) Save(ctx context.Context) (*Transaction, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TransactionUpdateOne) SaveX(ctx context.Context) *Transaction {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TransactionUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TransactionUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (tuo *TransactionUpdateOne) sqlSave(ctx context.Context) (_node *Transaction, err error) {
	_spec := sqlgraph.NewUpdateSpec(transaction.Table, transaction.Columns, sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Transaction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transaction.FieldID)
		for _, f := range fields {
			if !transaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Title(); ok {
		_spec.SetField(transaction.FieldTitle, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Amount(); ok {
		_spec.SetField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.AddedAmount(); ok {
		_spec.AddField(transaction.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := tuo.mutation.Description(); ok {
		_spec.SetField(transaction.FieldDescription, field.TypeString, value)
	}
	if tuo.mutation.DescriptionCleared() {
		_spec.ClearField(transaction.FieldDescription, field.TypeString)
	}
	if value, ok := tuo.mutation.Date(); ok {
		_spec.SetField(transaction.FieldDate, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.CategoryId(); ok {
		_spec.SetField(transaction.FieldCategoryId, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedCategoryId(); ok {
		_spec.AddField(transaction.FieldCategoryId, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AccountId(); ok {
		_spec.SetField(transaction.FieldAccountId, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.AddedAccountId(); ok {
		_spec.AddField(transaction.FieldAccountId, field.TypeInt, value)
	}
	if value, ok := tuo.mutation.UserId(); ok {
		_spec.SetField(transaction.FieldUserId, field.TypeString, value)
	}
	if value, ok := tuo.mutation.GetType(); ok {
		_spec.SetField(transaction.FieldType, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Status(); ok {
		_spec.SetField(transaction.FieldStatus, field.TypeString, value)
	}
	if tuo.mutation.StatusCleared() {
		_spec.ClearField(transaction.FieldStatus, field.TypeString)
	}
	if value, ok := tuo.mutation.Currency(); ok {
		_spec.SetField(transaction.FieldCurrency, field.TypeString, value)
	}
	if tuo.mutation.CurrencyCleared() {
		_spec.ClearField(transaction.FieldCurrency, field.TypeString)
	}
	_node = &Transaction{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
